nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:8080', 'http://127.0.0.1:8080']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['http://localhost:8080', 'http://127.0.0.1:8080']
